apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datastore-app
  namespace: datastore-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - datastore.vdc-cloud.de
      secretName: datastore-app-tls
  rules:
    - host: datastore.vdc-cloud.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: datastore-app
                port:
                  number: 80
